### PR TITLE
[CPS-6393] fix(resync): resync the release controller when occured unknown error (#152)

### PR DESCRIPTION
**Pull request by whalecold**
* [CPS-6393]fix(resync): resync the release controller when occured unknown error

* use time.During instead of int32

**What this PR does / why we need it**:

backport  https://github.com/caicloud/rudder/pull/152

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to # 

**Special notes for your reviewer**:

/cc @qianlei90

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
@qianlei90 @hezhizhen PATL

**Comment by hezhizhen** [comment]
LGTM

**Pull request merged**
