### PR TITLE
feat(deploy): recreate deploy when deploy's spec.selector changed

### PR DESCRIPTION
**Pull request by whalecold**
**What this PR does / why we need it**:

fix(deploy): recreate deploy when deploy's spec.selector changed

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @hezhizhen @zxq-bit 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
最后的问题引起不是由于 spec.selector 变化引起的，所以这个 pr 暂时不急着合并。

**Comment by hezhizhen** [comment]
LGTM

**Comment by hezhizhen** [comment]
close ?

**Pull request closed without merging**
