### PR TITLE
[release-0.3] fix(*): remove caimake (#138)

### PR DESCRIPTION
**Pull request by whalecold**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
CI 过了 @hezhizhen @qianlei90 
我把基础镜像从 1.9 改到了 1.10

**Comment by hezhizhen** [comment]
LGTM

**Pull request merged**
