### PR TITLE
[CPS-7402] feat(qps): QPS from go-common NewFromConfig

### PR DESCRIPTION
**Pull request by qianlei90**
**What this PR does / why we need it**:

- 从 master 分支 cherrypick QPS 的 [commit](https://github.com/caicloud/rudder/commit/97a963bb07503be42ae07a2a969de535110398a6) 到 release-0.4 (CPS 2.10) 分支
- 从 master 分支 cherrypick Makefile 规范化的 commit

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to http://jira.caicloud.xyz/browse/CPS-7402

**Special notes for your reviewer**:

/cc @whalecold @hezhizhen 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
LGTM

**Comment by qianlei90** [comment]
补上了 Makefile 规范化，PTAL @whalecold

**Comment by whalecold** [comment]
需要重新 push 下 @qianlei90

**Pull request merged**
