### PR TITLE
chore(Makefile): remove build target release-cli

### PR DESCRIPTION
**Pull request by qianlei90**
**What this PR does / why we need it**:

不再构建 release-cli 

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @whalecold 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hezhizhen** [comment]
cmd/ 下的内容不删掉吗？

**Comment by qianlei90** [comment]
> cmd/ 下的内容不删掉吗？

先留着吧，怕以后什么时候要用到这个 release-cli

**Pull request merged**
