### PR TITLE
chore: change base image

### PR DESCRIPTION
**Pull request by whalecold**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hezhizhen** [comment]
改的是 master？

**Comment by hezhizhen** [comment]
LGTM

**Comment by whalecold** [comment]
@qianlei90 PTAL

**Pull request merged**
